apiVersion: mig.or-sim.io/v1alpha1
kind: ArrivalSnapshot
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"mig.or-sim.io/v1alpha1","kind":"ArrivalSnapshot","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"migrant-go","mig.or-sim.io/experiment":"ampere-exact-slot"},"name":"exp-ampere-exact-slot-v3","namespace":"or-sim"},"spec":{"epoch":"102","source":"experiment-arrival-rate","targetArrival":{"gpt2":0.12,"llama":0.04},"unit":"requests_per_second","windowSeconds":60}}
  creationTimestamp: "2026-05-28T06:03:22Z"
  generation: 1
  labels:
    app.kubernetes.io/name: migrant-go
    mig.or-sim.io/experiment: ampere-exact-slot
  name: exp-ampere-exact-slot-v3
  namespace: or-sim
  resourceVersion: "6105050"
  uid: 3fc951b0-290a-41c2-bcde-b99eb9199d7b
spec:
  epoch: "102"
  source: experiment-arrival-rate
  targetArrival:
    gpt2: 0.12
    llama: 0.04
  unit: requests_per_second
  windowSeconds: 60
