apiVersion: mig.or-sim.io/v1alpha1
kind: MigPlan
metadata:
  name: stage0
  namespace: or-sim
spec:
  dryRun: true
  planner: phase_greedy
  scenario: stage0
  scenarioConfigMap: scenario-stage0
  outputStateConfigMap: target0-state
