apiVersion: mig.or-sim.io/v1alpha1
kind: MigPlan
metadata:
  name: stage2
  namespace: or-sim
spec:
  dryRun: true
  planner: phase_greedy
  scenario: stage2
  scenarioConfigMap: scenario-stage2
  sourceStateConfigMap: target1-state
  outputStateConfigMap: target2-state
