FROM python:3.13-slim

WORKDIR /app
COPY planner-engine/requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt
COPY planner-engine/app /app

EXPOSE 8080
CMD ["python", "/app/server.py"]
